project_id = "nohbdayalsposkwwxxuo"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-auth]
verify_jwt = false

[functions.whatsapp-reminders]
verify_jwt = false
